"""Initial migration

Revision ID: 21b76b7bb94b
Revises: 
Create Date: 2024-01-06 01:41:04.170132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b76b7bb94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('col1', sa.Integer(), nullable=False),
    sa.Column('col2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_data')
    # ### end Alembic commands ###
