"""Updated the models

Revision ID: d4d2f440b372
Revises: 21b76b7bb94b
Create Date: 2024-01-06 02:54:41.789627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d2f440b372'
down_revision = '21b76b7bb94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('col2')
        batch_op.drop_column('col1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('col1', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('col2', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('pixel_data')

    # ### end Alembic commands ###
